### PR TITLE
feat(query): add regex compare operator

### PR DESCRIPTION
**Pull request by naorpeled**
- added the =~ operator, which allows matching regular expressions against inputs.

### CODE REVIEW

**Comment by naorpeled** [comment]
Hey @AvitalTamir,
the PR is now ready for review 🙏

**Comment by AvitalTamir** [comment]
@naorpeled looks good!
Can you please add this (and `CONTAINS` while you're at it) to `docs/LANGUAGE.md` in the `WHERE` clause section?

**Review by AvitalTamir — CHANGES_REQUESTED** [review]
Ahmed

Very good visual communication skills, presented both CI/CD and networking diagrams that were good looking, made to (almost) perfection and told a clear story

Good verbal communication, outgoing, nice person.

Held good conversation about Kubernetes internals, presented good knowledge of the control plane and expressed a lot of curiosity when discussing the aspects he didn’t already know, gives an impression that he’s a fast learner and very passionate about our line of work.

Was seeking feedback continuously and at the end of the conversation and took it very well.

My only pet peeve was that for some questions he answered without a clear stand of why he did something the way he did (got a couple of “this is what they asked of us…”). I gave the feedback that he shouldn’t be afraid to stand behind his decisions and that optimizations could always be made - he was receptive and took criticism very well.

I think he fits well with the develeap culture and would be a good interviewee. all in all would recommend.

**Comment by naorpeled** [comment]
> @naorpeled Can you add this to `docs/LANGUAGE.md` (and `CONTAINS` too while you're at it)?

Sure thing

**Review by AvitalTamir — APPROVED** [review]
Cheers! Great work 💯

**Pull request merged**
