### PR TITLE
[ISSUE-104] fix bug: `cyphernetes shell -A` results in `panic`

### LINKED ISSUE #104: bug: `cyphernetes shell -A` results in`panic`
Issues observed:
1. When running `cyphernetes shell -A` or `cyphernetes shell --all-namespaces` and a query, it results in a panic.
2. When running `cyphernetes shell -A` or `cyphernetes shell --all-namespaces`, the namespace defaults to `default`

```
jameskim:~/workspace/cyphernetes/dist $ ./cyphernetes shell -A

                __                    __
 ______ _____  / /  ___ _______  ___ / /____ ___
/ __/ // / _ \/ _ \/ -_) __/ _ \/ -_) __/ -_|_-<
\__/\_, / .__/_//_/\__/_/ /_//_/\__/\__/\__/___/
   /___/_/ Interactive Shell

🔎 fetching resource specs from openapi... done!

Type 'exit' or press Ctrl-D to exit
Type 'help' for information on how to use the shell

(docker-desktop) default » MATCH (p:Pods) RETURN p.metadata.name;

2024/10/08 21:10:08 Lexing...  77  ( M )
2024/10/08 21:10:08 Scanned token: -2
2024/10/08 21:10:08 Token text: �
2024/10/08 21:10:08 Returning MATCH token
2024/10/08 21:10:08 Lexing...  32  (   )
2024/10/08 21:10:08 Scanned token: 40
2024/10/08 21:10:08 Token text: (
2024/10/08 21:10:08 Returning LPAREN token
2024/10/08 21:10:08 Lexing...  112  ( p )
2024/10/08 21:10:08 Scanned token: -2
2024/10/08 21:10:08 Token text: �
2024/10/08 21:10:08 Returning IDENT token with value: p
2024/10/08 21:10:08 Lexing...  58  ( : )
2024/10/08 21:10:08 Scanned token: 58
2024/10/08 21:10:08 Token text: :
2024/10/08 21:10:08 Returning COLON token
2024/10/08 21:10:08 Lexing...  80  ( P )
2024/10/08 21:10:08 Scanned token: -2
2024/10/08 21:10:08 Token text: �
2024/10/08 21:10:08 Returning IDENT token with value: Pods
2024/10/08 21:10:08 Lexing...  41  ( ) )
2024/10/08 21:10:08 Scanned token: 41
2024/10/08 21:10:08 Token text: )
2024/10/08 21:10:08 Returning RPAREN token
2024/10/08 21:10:08 Lexing...  32  (   )
2024/10/08 21:10:08 Scanned token: -2
2024/10/08 21:10:08 Token text: �
2024/10/08 21:10:08 Returning RETURN token
2024/10/08 21:10:08 Lexing...  32  (   )
2024/10/08 21:10:08 Returning JSONPATH token with value: p.metadata.name
2024/10/08 21:10:08 Lexing...  -1  ( � )
2024/10/08 21:10:08 Scanned token: -1
2024/10/08 21:10:08 Token text: �
2024/10/08 21:10:08 Returning EOF token
2024/10/08 21:10:08 Lexing...  -1  ( � )
2024/10/08 21:10:08 Zero (buffered EOF)
2024/10/08 21:10:08 Node pattern found. Name: p Kind: Pods
2024/10/08 21:10:08 Listing resources of kind: Pods with fieldSelector:  and labelSelector:
panic: interface conversion: interface {} is nil, not []map[string]interface {}

goroutine 1 [running]:
github.com/avitaltamir/cyphernetes/pkg/parser.(*QueryExecutor).processNodes(0xc000450630, 0xc00078e190, 0xc000a512d8)
        /Users/jameskim/workspace/cyphernetes/pkg/parser/k8s_query.go:710 +0x707
github.com/avitaltamir/cyphernetes/pkg/parser.(*QueryExecutor).Execute(0xc000450630, 0xc00023e150, {0x0?, 0xaa7e37a?})
        /Users/jameskim/workspace/cyphernetes/pkg/parser/k8s_query.go:84 +0xe05
main.executeStatement({0xc001a16090?, 0x10?})
        /Users/jameskim/workspace/cyphernetes/cmd/cyphernetes/shell.go:553 +0x95
main.processQuery({0xc001a16090, 0x25})
        /Users/jameskim/workspace/cyphernetes/cmd/cyphernetes/shell.go:490 +0x231
main.runShell(0xc0002eaa00?, {0xbc31de6?, 0x4?, 0xbc31dea?})
        /Users/jameskim/workspace/cyphernetes/cmd/cyphernetes/shell.go:415 +0x1678
github.com/spf13/cobra.(*Command).execute(0xcf01e20, {0xc00044da70, 0x1, 0x1})
        /Users/jameskim/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0xcf01860)
        /Users/jameskim/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/jameskim/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.Execute()
        /Users/jameskim/workspace/cyphernetes/cmd/cyphernetes/root.go:23 +0x1a
main.main()
        /Users/jameskim/workspace/cyphernetes/cmd/cyphernetes/main.go:7 +0xf
```

### PR DESCRIPTION
**Pull request by jameskim0987**
Fixes #104 

Changes made in this PR:
1. Fix `panic` for `cyphernetes shell -A`
2. Prompt the red `ALL NAMESPACES` shellprompt after starting shell
3. [ TODO ]: add tests

### CODE REVIEW

**Review by AvitalTamir — APPROVED** [review]

**Comment by jameskim0987** [comment]
Hi @AvitalTamir, I have some updates on the test issue -- I think I'm halfway there understanding the core of the issue. 

Try the following so we are on the same page:
1. In `cmd/cyphernetes/main_test.go`, move this test `TestCyphernetesShellWithHelpFlag` up top so it is the first test in `main_test.go`
2. Run the tests
3. Now you should be able to observe that the subsequent tests that involve `cyphernetes shell ...` which are `TestCyphernetesShellNoFlag`, `TestCyphernetesShellWithAllNamespacesFlag`, and `TestCyphernetesShellWithNamespaceFlag` all fail. 
4. Now if you move `TestCyphernetesShellWithHelpFlag` in between those 3 failed tests, then the tests after `TestCyphernetesShellWithHelpFlag` fails. This shows that `TestCyphernetesShellWithHelpFlag` is the main issue.

After analyzing the code and debugging through the tests, one thing that stood out to me was that after `TestCyphernetesShellWithHelpFlag`, the subsequent tests were using **the same instance of `rootCmd`** ( which is a pointer to cobra.Command ). Apart from it being a global variable, another way I verified out about this was, on the subsequent tests, the `rootCmd` object contained a non-nil value for `c.helpCommand` ( `c.helpCommand` is initialized through `c.InitDefaultHelpCmd()` and `c.InitDefaultHelpFlag()` )

and because that "help" flag remained as part of the Command and the same Command was being referenced, it was constantly returning `true` for `helpVal` and handling the execution there **as if** the arguments were "cyphernetes shell --help".

https://github.com/spf13/cobra/blob/main/command.go#L898-L907

Now, going back to the tests in `main_test.go`, I have some brainstorming questions: 
1. Since we are invoking `main()` for each test, does it share any objects without a clean teardown across tests?
2. How could we make the tests such that we avoid objects being shared explicitly / implicitly across tests ( ex: `rootCmd` )?

I'm quite positive that this is the crux of the issue but not sure what would be the best approach to solve it. Let me know your thoughts.

**Comment by AvitalTamir** [comment]
@jameskim0987 thanks for catching this! I looked around for a way to tear down or at least clear the flags but didn't manage - so to work around it I tried sandboxing each test in it's own go execution, it's not beautiful but it works.
What do you think?
https://github.com/AvitalTamir/cyphernetes/blob/issue-104-fix-shell-A-flag/cmd/cyphernetes/main_test.go

(I also addressed the pipeline issue in this branch - It was the Makefile piping test outputs to sed... Removed it.)

Let me know what you think.

**Comment by jameskim0987** [comment]
@AvitalTamir I agree that we can lose the check for the help flag. I was actually on the fence about whether we should test it or not. Initially I thought we should cover it for the sake of completeness but since it's auto generated I think it is safe to drop it ( unless in the future we decide to add custom `help` output ). 

Looking at your sandboxed and refactored test code though, I think it is ok to leave it since it's already there.

Side note, from the tests I had, when I removed the help check test and ran the entire tests, `TestExecuteNoArgs` was failing so I think we should keep your test changes.

In short, looks good to me!

**Comment by AvitalTamir** [comment]
Great, same here! You can mark it ready for review and I'll merge :)

**Review by AvitalTamir — APPROVED** [review]

**Comment by AvitalTamir** [comment]
Thanks @jameskim0987! This is very exciting!

I enjoyed working with you on this. Thanks again for reporting, and resolving this issue 🔥

**Comment by jameskim0987** [comment]
@AvitalTamir Likewise! Finding and resolving bugs is pretty exciting and thanks for your supervision. I'm glad to contribute!

**Pull request merged**
