### PR TITLE
feat(query): support CONTAINS operator

### LINKED ISSUE #105: Support CONTAINS operator
In WHERE clauses, add support for the CONTAINS keyword that will do partial matches on strings

### PR DESCRIPTION
**Pull request by naorpeled**
closes #105

### CODE REVIEW

**Comment by AvitalTamir** [comment]
Hey @naorpeled looks like a good start, next I think you need to return this token from the lexer (look for large switch case in `lexer.go` where is returns `>=`, `>`, other keywords like `RETURN` etc. and add it there.
From there you should be able to implement the logic in the query engine.

**Comment by naorpeled** [comment]
Hey @AvitalTamir,
thanks for the pointers!

Had an issue with my local setup so it took me a bit longer, sorry for the delay.
The PR is ready for a review.

Are you okay with the regex implementation, or would you rather have only a partial match?

I kinda like the following:
```bash
MATCH (d:Deployment)
WHERE d.spec.template.metadata.labels.app CONTAINS "^admin.*api"
RETURN d.spec.template.metadata.labels.app AS deployment_name, d.spec.replicas AS replica_count;
```

**Comment by AvitalTamir** [comment]
Hey @naorpeled first of all what a great contribution! Thank you so much for this one.

I actually thought this would be implemented using `strings.Contains` but I honestly LOVE the ability to do regex... maybe we should change the operator to `=~` so it's ultra-clear to the user? We can add both... let me know your thoughts, in any case I love this.

**Comment by naorpeled** [comment]
> Hey @naorpeled first of all what a great contribution! Thank you so much for this one.
> 
> I actually thought this would be implemented using `strings.Contains` but I honestly LOVE the ability to do regex... maybe we should change the operator to `=~` so it's ultra-clear to the user? We can add both... let me know your thoughts, in any case I love this.

Oh, that's a great idea!!! Love it.
Will adjust this PR to utilize `strings.Contains` and create another one that implements the `=~` operator.

**Comment by naorpeled** [comment]
@AvitalTamir done, also tested locally, let me know what you think.

**Comment by AvitalTamir** [comment]
Incredible, I'm AFK today but will check this out as soon as I'm back tonight 😎

**Comment by naorpeled** [comment]
> Incredible, I'm AFK today but will check this out as soon as I'm back tonight 😎

Sounds good to me, no rush 😎

**Review by AvitalTamir — CHANGES_REQUESTED** [review]
@naorpeled missing adding the `CONTAINS` keyword to the painter in the shell.
(run `cyphernetes shell` and use it in a query - we want the CONTAINS keyword to get colored and uppercased. You can find the section where we list the cyphernetes keywords in the painter function and just add it there)

**Comment by naorpeled** [comment]
> @naorpeled missing adding the `CONTAINS` keyword to the painter in the shell. (run `cyphernetes shell` and use it in a query - we want the CONTAINS keyword to get colored and uppercased. You can find the section where we list the cyphernetes keywords in the painter function and just add it there)

done 🙏

**Review by AvitalTamir — APPROVED** [review]

**Comment by AvitalTamir** [comment]
Looking very good @naorpeled!
Very exciting, congratulations and thank you so much for your first Cyphernetes contribution, merging ❤️👑🏅

**Pull request merged**
